// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("CIPHERPrototype6")>]
[<assembly: AssemblyProductAttribute("CIPHERPrototype6")>]
[<assembly: AssemblyDescriptionAttribute("CIPHERPrototype6")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "CIPHERPrototype6"
    let [<Literal>] AssemblyProduct = "CIPHERPrototype6"
    let [<Literal>] AssemblyDescription = "CIPHERPrototype6"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
